###############################
#     Hades Configuration     #
###############################
# This is the configuration file of Hades Anti-Cheat

# Hades is a very configurable anticheat. All the punish commands and max VL's are configurable.
# Hades supports logging very well. It can write the logs to the console or a file.
# Hades support change of base command, prefix, punish announcements and more!
# IMPORTANT: If you don't know what something does, don't change it.

#Anticheat Test Mode
#If true, this will disable punishments completely and will
#automatically enable alerts for anyone who joins (dev alerts)
test-mode: false

#Language Configuration
lang:
  prefix: '&c[Hades]'
  no-permission: '&cNo permission.'
  base-message-color: '&c'
  enable-alerts-message: '&7You have toggled alerts &con &7with flag setting &c%flagsetting%&7.'
  disable-alerts-message: '&7You have toggled alerts &coff&7.'

#System Configuration
system:
  logging:
    log-format: '[%time%] %player% failed %check% (%checktype%) VL:(%vl%) INFO:(%info%)'
    log-to-file: true
    log-to-console: false

report:
  enabled: true

#VPN Protection
anti-vpn:
  enabled: true
  punish-command: 'kick %player% &cVPNs are not allowed on this server!'

#Combat Patch Values
Max-CPS: 18
Max-Reach: 3.2

#Check Configuration
#NOTE: Experimental checks are preset to not punish players
checks:
  exempt-players: false
  broadcast-punishments: true
  broadcast-message: '%newline%&cHades &7has auto-banned &c%player% &7for: &4%check%%newline% '
  flag-format: '&8(&c&l!&r&8) &c%player% &7failed &c%check% &7(&c%checktype%&7) &cx%vl%'
  dev-flag-format: '&8(&c&l!&r&8) &c%player% &7failed &c%check% &7(&c%checktype%&7) &cx%vl% &7[PING=%ping%,TPS=%tps%&7,INFO=%info%]'
  detections:
    angle:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    autoblock:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    aura:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    autoclicker:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    criticals:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    killaura:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    noswing:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    pattern:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    reach:
      enabled: true
      punishable: false
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    velocity:
      enabled: true
      punishable: false
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    fastladder:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix Unfair Advantage'
    flight:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    invalid:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Avantage'
    motion:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    noslow:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    scaffold:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    speed:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    sprint:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    client:
      enabled: true
      punishable: true
      max-violations: 1
      punish-command: 'ban %player% %prefix% Hacked Client'
    fastuse:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    interactreach:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    inventorymove:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    nofall:
      enabled: true
      punishable: true
      max-violations: 5
      punish-command: 'ban %player% %prefix% Unfair Advantage'
    timer:
      enabled: true
      punishable: true
      max-violations: 20
      punish-command: 'ban %player% %prefix% Unfair Advantage'