###############################
#     Hades Configuration     #
###############################
# This is the configuration file of Hades Anti-Cheat

# Hades is a very configurable anticheat. All the punish commands and max VL's are configurable.
# Hades supports logging very well. It can write the logs to a file or even a MySQL server.
# Hades support change of base command, prefix, punish announcements and more!
# IMPORTANT: If you don't know what does something does don't use it.

# Mitigate: Mitigate means lagback or canceling hits. If you want to make Hades silent or if you want it to false less you can disable it.

#Language Configuration
lang:
  prefix: '&8[&fHades&8] &7'
  no-permission: '&cNo permission.'
  base-message-color: '&c'
  flag-format: '%prefix%&f%player% &7has failed &f%check% &8<&7%checktype%&8> &7VL:%vl%'
  experimental-notation: '*'
  broadcast-message: '%newline%&7User &f%player% &7was automatically banned by &fHades &7for &fCheating&7.%newline% '

#System Configuration
system:
  logging:
    log-format: '[%time%] %player% failed %check% (%checktype%) VL:(%vl%) INFO:(%info%)'
    log-to-console: false
    file:
      enabled: true
      path: '\\logs'
      file-name: 'log.txt'
    mysql:
      enabled: false
      host: localhost
      port: 3306
      pool: 4
      database: Hades
      auth:
        username: root
        password: ''
#VPN Protection
anti-vpn:
  enabled: true
  punish-command: 'kick %player% &cVPNs are not allowed on this server!'

#Check Values
Max-CPS: 20
Max-Reach: 3.4

#Check Configuration
#NOTE: Experimental checks are preset to not punish players
checks:
  broadcast-punishments: true
  detections:
    aim:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    aura:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      d:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      e:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      f:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      g:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    autoclicker:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      d:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    criticals:
      mitigate: true
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    reach:
      mitigate: true
      a:
        enabled: true
        punishable: false
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    velocity:
      a:
        enabled: true
        punishable: false
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    fly:
      mitigate: true
      a:
        enabled: true
        punishable: true
        max-vl: 20
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-vl: 20
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-vl: 20
        punish-command: 'ban %player% %prefix%Cheating'
    invalid:
      mitigate: true
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      d:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      e:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    noslow:
      mitigate: true
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    scaffold:
      mitigate: true
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    speed:
      mitigate: true
      a:
        enabled: true
        punishable: true
        max-vl: 20
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-vl: 20
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-vl: 20
        punish-command: 'ban %player% %prefix%Cheating'
      d:
        enabled: true
        punishable: true
        max-vl: 20
        punish-command: 'ban %player% %prefix%Cheating'
    sprint:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    fastladder:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    invmove:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    fastuse:
      mitigate: true
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    nofall:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    timer:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    interactreach:
      a:
        enabled: true
        punishable: true
        max-vl: 10
        punish-command: 'ban %player% %prefix%Cheating'
    vape:
      a:
        enabled: true
        punishable: true
        max-vl: 1
        punish-command: 'ban %player% %prefix%Cheating'