###############################
#     Hades Configuration     #
###############################
# This is the configuration file of Hades Anti-Cheat

# Hades is a very configurable anticheat. All the punish commands and max VL's are configurable.
# Hades supports logging very well. It can write the logs to a file or even a MySQL server.
# Hades support change of base command, prefix, punish announcements and more!
# IMPORTANT: If you don't know what does something does don't use it.

# Mitigate: Mitigate means lagback or canceling hits. If you want to make Hades silent or if you want it to false less you can disable it.

#Language Configuration
lang:
  prefix: '&c[Hades]'
  no-permission: '&cNo permission.'
  base-message-color: '&c'
  enable-alerts-message: '&7You have toggled alerts &aon&7.'
  disable-alerts-message: '&7You have toggled alerts &coff&7.'

#System Configuration
system:
  #Example Permission: 'basepermission'.exempt.checks
  base-permission: 'hades'
  logging:
    log-format: '[%time%] %player% failed %check% (%checktype%) VL:(%vl%) INFO:(%info%)'
    log-to-file: true
    log-to-console: false

#VPN Protection
anti-vpn:
  enabled: true
  punish-command: 'kick %player% &cVPNs are not allowed on this server!'

#Combat Patch Values
Max-CPS: 15
Max-Reach: 3.2

#Check Configuration
#NOTE: Experimental checks are preset to not punish players
checks:
  exempt-players: false
  broadcast-punishments: true
  broadcast-message: '%newline%&cHades &7has detected &c%player% &7cheating and removed them from the network.%newline% '
  flag-format: '&8(&c&l!&r&8) &c%player% &7failed &c%check% %checktype% &8(&c%ping%ms&8)'
  dev-flag-format: '&8(&c&l!&r&8) &c%player% &7failed &c%check% %checktype% &8(&c%ping%ms&8) &7VL:%vl%'
  detections:
    aura:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      d:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      e:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      f:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      g:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    autoclicker:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      d:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    criticals:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    reach:
      a:
        enabled: true
        punishable: false
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    velocity:
      a:
        enabled: true
        punishable: false
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    fly:
      a:
        enabled: true
        punishable: true
        max-violations: 20
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-violations: 20
        punish-command: 'ban %player% %prefix%Cheating'
    motion:
      a:
        enabled: true
        punishable: true
        max-violations: 20
        punish-command: 'ban %player% %prefix%Cheating'
    invalid:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      d:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      e:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    noslow:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    scaffold:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    speed:
      a:
        enabled: true
        punishable: true
        max-violations: 20
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-violations: 20
        punish-command: 'ban %player% %prefix%Cheating'
      c:
        enabled: true
        punishable: true
        max-violations: 20
        punish-command: 'ban %player% %prefix%Cheating'
      d:
        enabled: true
        punishable: true
        max-violations: 20
        punish-command: 'ban %player% %prefix%Cheating'
    sprint:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    fastladder:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    invmove:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    fastuse:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    nofall:
      a:
        enabled: true
        punishable: true
        max-violations: 5
        punish-command: 'ban %player% %prefix%Cheating'
    timer:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
      b:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    interactreach:
      a:
        enabled: true
        punishable: true
        max-violations: 10
        punish-command: 'ban %player% %prefix%Cheating'
    vape:
      a:
        enabled: true
        punishable: true
        max-violations: 1
        punish-command: 'ban %player% %prefix%Cheating'